Mark downloads without preparedIds as PREPARING not RESTORING #40
ral-facilities/datagateway-download-api pull request #43
Opened 2024-11-22 10:31 UTC by patrick-austin

- Jobs without preparedIds to be marked RESTORING get marked PREPARING instead, so that they get assigned one by the usual status checks.

Closes #40

2024-12-11 15:48 UTC, kevinphippsstfc requested changes

2024-12-11 15:48 UTC, kevinphippsstfc commented on src/test/java/org/icatproject/topcat/AdminResourceTest.java
> +		response = adminResource.getDownloads(facilityName, adminSessionId, "1 = 1");
Can a value of null be passed for the queryOffset? I was confused at first as to what the "1 = 1" was for but found it in other tests with a comment, so if null doesn't work, then at least a comment as to what it's for would be useful here.

2025-01-02 14:33 UTC, patrick-austin commented on src/test/java/org/icatproject/topcat/AdminResourceTest.java
> +		response = adminResource.getDownloads(facilityName, adminSessionId, "1 = 1");
I based the test on the  other existing tests which used `"1 = 1"`, taking the comment on faith (but not copying it across to the new test). Having had a look though it seems like the code should handle null values - these tests still passed for me locally without it so I've removed it in all three places. Maybe it didn't used to work, the comments were written, then the null case handling was added but the tests were never updated? In any case hopefully they are all simpler now.

2025-01-06 10:46 UTC, kevinphippsstfc approved these changes

2025-01-06 10:48 UTC, merged