Poll and prepare queued Downloads #38
ral-facilities/datagateway-download-api pull request #45
Opened 2024-11-25 10:44 UTC by patrick-austin

Branched from #39 due to those test failures breaking the tests added as part of this PR.

- Add run.properties setting for the maximum number queued jobs to schedule concurrently
- After existing `updateStatuses` check, `startQueuedDownloads` up to the limit above minus any RESTORING Downloads
- Refactor existing query in `updateStatuses` for clarity
- Re-enabled `StatusCheckTest` in pom.xml
- Removed references to `em` in `StatusCheckTest` and use the `downloadRepository` instead, like the other tests
  - Mostly this did not require changes to any test logic, just the utility functions, but did alter updates to Downloads in the tests to either create with those values in the first place or explicitly create new Downloads
- Tests in `StatusCheckTest` now use `finally` to remove Downloads created for the test, as failure in one test meant bad data caused subsequent tests to fail
- Changes to how the dummy Downloads are created to support arbitrary preparedIds and statuses, for testing the new functions
- Whitespace changes caused by auto-formatting my changes (tried to limit this to only functions relevant to this change)

Closes #38

2024-12-18 15:35 UTC, kevinphippsstfc requested changes

2024-12-18 15:35 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +      return;
I feel a log message is needed here, indicating why nothing is being taken from the queue to help somebody debug why this functionality is not working/disabled. (Maybe they have forgotten to add the new property to the config file for example.)

2024-12-18 15:35 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +        return;
Likewise a log message here would help with debugging

2024-12-18 15:35 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +    for (Download queuedDownload : queuedDownloads) {
And perhaps another log message here somewhere saying how many queued downloads are being unqueued (if that's even a word)

2024-12-18 15:35 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +      queuedQueryString += " order by download.createdAt limit " + Integer.toString(freeActiveDownloads);
Does the limit part of this JPQL query actually work? 
From my understanding it is not standard JPQL (the limit clause in ICAT queries is an addition/extension to JPQL I believe).
You might need to replace this with a call to:
queuedDownloadsQuery.setMaxResults(limit)
after the query object has been created below.

2025-01-03 10:34 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +      int maxActiveDownloads = Integer.valueOf(properties.getProperty("queue.maxActiveDownloads", "0"));
That was sort of the intention - idea being updating to the new version won't actually change anything unless you "opt in" by setting a value in the config, so it's less likely to cause unexpected behaviour if you aren't aware of/don't want the new feature.

But I don't particularly mind, and I'm happy to set the default to 1 instead (since this also shouldn't have any effect unless you "opt in" by using the new submission endpoint, it will just execute some additional database queries when polling).

2025-01-03 10:36 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +      return;
Have added a debug level log here (as it doesn't contain "useful" information about the current state of the queue, just that it's disabled, so will always be the same and might clog the log if it were info), happy to increase the level though.

2025-01-03 10:40 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +        return;
Added an info level log here detailing the current number of RESTORING downloads and that this is over the limit.

2025-01-03 10:41 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +    for (Download queuedDownload : queuedDownloads) {
Have added an info level log here.

2025-01-03 10:46 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/StatusCheck.java
> +      queuedQueryString += " order by download.createdAt limit " + Integer.toString(freeActiveDownloads);
No it doesn't - had missed this (a positive limit greater than the number of RESTORING downloads) from the test cases, and overlooked the fact that this is run against the download DB and not via the IcatClient/server/DB so doesn't obey the same syntax.

Have added this missing test case and used the proper method as suggested.

2025-01-06 11:52 UTC, kevinphippsstfc approved these changes

2025-01-06 13:49 UTC, merged