Implement queueFiles endpoint #50
ral-facilities/datagateway-download-api pull request #51
Opened 2024-12-03 12:29 UTC by patrick-austin

Branched from #49 due to re-used code which has been refactored here.

- Add endpoint to UserResource to submit multiple files
- Add function to IcatClient to getDatafiles for the above
- Refactored code common to this and the visitId submission

Closes #50

2025-01-14 09:13 UTC, kevinphippsstfc requested changes

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +	 * Utility method for submitting an unformatted query to the entityManager
What do you mean by an "unformatted" query? One that hasn't been UTF8 encoded? Maybe non/un(?) encoded would be a better description.

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +	 * @param query Unformatted String query to submit
"Unformatted" again

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/IcatClient.java
>  				throw new NotFoundException("Could not run getEntities got a 404 response");
getEntities -> submitQuery

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/web/rest/UserResource.java
> +	 * @param facilityName ICAT Facility.name
As per my comment on other PRs, I don't think users should have to specify the facility name, so can this be made into an optional form parameter instead?

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/web/rest/UserResource.java
> +		logger.info("queueVisitId called");
queueVisitId -> queueFiles

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/web/rest/UserResource.java
> +		long part = 1;
As per my comment on another PR, I think these values should have "L" after them.

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/web/rest/UserResource.java
> +				part += 1;
These values should have "L" after them.

2025-01-14 09:13 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/web/rest/UserResource.java
> +		String filename = formatQueuedFilename(facilityName, "files", part);
Can you check if this call is affected by any changes that might happen due to my comments about this method on the other PR.

2025-01-14 10:30 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +		StringBuilder stringBuilder = new StringBuilder();
I think this section creating the comma separated list can be replaced with:
String commaSepString = String.join(",", downloadIds);

2025-01-14 13:52 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +	 * Utility method for submitting an unformatted query to the entityManager
Yeah looking at it I think I've used it as a synonym for encoding? Will change.

2025-01-14 14:07 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +		StringBuilder stringBuilder = new StringBuilder();
I think I tried this without the `'` around the filename but it didn't work, as the strings needed to be single quoted for the JPQL. While using `join` gets the comma, it wouldn't add the single quotes. I suppose you could do:
```java
String commaSepString = String.join("','", downloadIds);
String finalString = "'" + commaSepString + "'";
```
It's less lines of code but I think it makes the need to single quote less explicit and so overall maybe isn't as clear - but I can change it to that if you think it would be better than what we have now?

2025-01-14 14:20 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +		StringBuilder stringBuilder = new StringBuilder();
Yes sorry I didn't spot that the filepaths need to be in single quotes here.
I would be happy with the whole thing on a single line eg:
`String commaSepString = "'" + String.join("','", files) + "'";`
Admittedly the single quotes do get lost somewhat in the double quotes but I much prefer it to the 8 lines that are currently there (which also have multiple places where single quotes are hiding in double quotes).

2025-01-14 14:31 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +		StringBuilder stringBuilder = new StringBuilder();
Actually I think this will probably be superseded by all the chunking stuff anyway.

2025-01-14 15:10 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/IcatClient.java
> +		StringBuilder stringBuilder = new StringBuilder();
As it stands in order to build those shorter lists I need to consider each file in turn, get its encoded length, compare against the chunk limit, decide whether to add to the current chunk or start a new one, then repeat. So I'll be iterating over the list of files to do that rather using join, but there's no point worrying about it now, can leave the details to the re-review.

2025-01-15 16:27 UTC, kevinphippsstfc approved these changes

2025-01-15 16:35 UTC, merged