Implement GET DownloadStatus endpoint #52
ral-facilities/datagateway-download-api pull request #54
Opened 2024-12-04 14:05 UTC by patrick-austin

Closes #52

2025-01-14 11:16 UTC, kevinphippsstfc requested changes

2025-01-14 11:16 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/web/rest/UserResource.java
> +	public Response getDownloadStatuses(@QueryParam("facilityName") String facilityName,
As with other PRs, can the facility name be made optional?

2025-01-14 11:16 UTC, kevinphippsstfc commented on src/test/java/org/icatproject/topcat/UserResourceTest.java
> +			Response response = userResource.getDownloadStatuses("LILS", sessionId, downloadIds);
I feel like as the download IDs is a list, the test ought to have more than one item in it.
And if the status were set different on those Downloads then it would also be possible to check that the statuses are returned in an order matching the request.
So that the code doesn't get too repetitive with creating the downloads, it might be nice to make use of the createDownload method that you created in one of the other PRs.

2025-01-15 09:04 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/web/rest/UserResource.java
> +	public Response getDownloadStatuses(@QueryParam("facilityName") String facilityName,
I think this one should be optional once it's merged onto the changes from #47 - it's using a `QueryParam` so can be left out, and the update `FacilityMap` functions will handle `null` values by returning the configured default.

2025-01-15 09:14 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/repository/DownloadRepository.java
> +		StringBuilder stringBuilder = new StringBuilder();
`String.join()` requires the second argument to be a `CharSequence` or `Iterable<? extends CharSequence>` - but we have a `List<Long>`, and `Long` doesn't extend `CharSequence`. To use `String.join` I think we'd need to first iterate over every id, get the `String` value, then join (unless there's a neater/more efficient way of casting):
```java
		List<String> stringDownloadIds = new ArrayList<>();
		downloadIds.forEach(downloadId -> {
			stringDownloadIds.add(downloadId.toString());
		});
		String joinedDownloadIds = String.join(",", stringDownloadIds);
```
I guess it's 2 lines shorter (so maybe looks nicer?) but I can only assume it's less efficient because we're looping twice . Let me know if you still prefer it and I can make the change (or not).

2025-01-15 09:40 UTC, kevinphippsstfc commented on src/main/java/org/icatproject/topcat/repository/DownloadRepository.java
> +		StringBuilder stringBuilder = new StringBuilder();
I think I prefer the shorter version as it's much simpler despite the slight inefficiency of looping twice.
It could be simplified even further using a standard for-each loop:
```
List<String> stringDownloadIds = new ArrayList<>(); 
for (Long downloadId : downloadIds) { 
    stringDownloadIds.add(downloadId.toString()); 
} 
String joinedDownloadIds = String.join(",", stringDownloadIds);
```
which gets rid of the (I find) rather awkward syntax of Lambda expressions.

2025-01-15 11:56 UTC, patrick-austin commented on src/test/java/org/icatproject/topcat/UserResourceTest.java
> +			Response response = userResource.getDownloadStatuses("LILS", sessionId, downloadIds);
Yes it would ensure it properly tests the String joining stuff above as well. Will refactor the dummyDownload functions from `StatusCheckTest` to `TestHelpers` so we can use them here as well.

2025-01-15 11:59 UTC, patrick-austin commented on src/main/java/org/icatproject/topcat/repository/DownloadRepository.java
> +		StringBuilder stringBuilder = new StringBuilder();
Sure, I can't see the inefficiency actually mattering/bottlenecking here, so happy to go for whatever is clearest to someone else reading the code

(I do actually like lambdas though... 😬 )

2025-01-16 13:04 UTC, kevinphippsstfc approved these changes

2025-01-16 14:06 UTC, merged